/**
 * This file is automatically generated using [XML2SCA] 
 * Contact : panxiao.tech@gmail.com
 * Web     : http://panxiao.tech/tools/xml2sca/
 * 
 * @file    sensor_adc_example/src/sca_tdf_sine.h
 * @author  Xiao Pan (pan@cs.uni-kl.de)
 * @date    10:46:05 Apr 16 2018
 * @section LICENSE License (ADD YOUR LICENSE HERE)
 *  
 * @section DESCRIPTION Description (ADD YOUR DESCRIPTION HERE)
 *          Example project of [XML2AMS]
 * 
 */


#ifndef sca_tdf_sine_h_
#define sca_tdf_sine_h_


#include <systemc-ams> 




SCA_TDF_MODULE(sca_tdf_sine) {
public:
	//! in/output ports
	 sca_tdf::sca_out<double>  pout_sine;         

	//! @brief Custom constructor ofsca_tdf_sine
	//! @para freq genertaed signal frequency [Hz], default set to 1Mhz
	//! @para amp output amplitude [volt], default set to 1.0
	//! @para offset output offset [volt], default set to 0.0
	sca_tdf_sine(sc_core::sc_module_name nm,
		double _freq = 1e6,
		double _amp = 1.0,
		double _offset = 0.0 );

protected:


private:
	 // Local variables for module parameters
	double p_freq;
	double p_amp;
	double p_offset;

	void set_attributes(); 
	void initialize(); 
	// void ac_processing(); 
	void processing(); 
	// void change_attributes(); 
	// void ac_processing(); 
	// void end_of_simulation();
    
    
    //<<< START OF USER-ADDED-CODE >>>>
    double  sample_time;
    double  actval;
    double  stepsize;
    //<<< END OF USER-ADDED-CODE >>>

};
#endif 
