/**
 * This file is automatically generated using [XML2SCA] 
 * Contact : panxiao.tech@gmail.com
 * Web     : http://panxiao.tech/tools/xml2sca/
 * 
 * @file    sensor_adc_example/src/sca_tdf_drain.h
 * @author  Xiao Pan (pan@cs.uni-kl.de)
 * @date    10:46:05 Apr 16 2018
 * @section LICENSE License (ADD YOUR LICENSE HERE)
 *  
 * @section DESCRIPTION Description (ADD YOUR DESCRIPTION HERE)
 *          Example project of [XML2AMS]
 * 
 */


#ifndef sca_tdf_drain_h_
#define sca_tdf_drain_h_


#include <systemc-ams> 




SCA_TDF_MODULE(sca_tdf_drain) {
public:
	//! in/output ports
	 sca_tdf::sc_in<uint16_t>  pin_d;             

	//! @brief Custom constructor ofsca_tdf_drain
	sca_tdf_drain(sc_core::sc_module_name nm );





protected:




private:
	 // Local variables for module parameters




	void set_attributes(); 
	void initialize(); 
	void processing(); 
	// void change_attributes(); 
	// void ac_processing(); 
	// void end_of_simulation(); 
};
#endif 
