/**
 * This file is automatically generated using [XML2SCA] 
 * Contact : panxiao.tech@gmail.com
 * Web     : http://panxiao.tech/tools/xml2sca/
 * 
 * @file    sensor_adc_example/src/sca_tdf_gnd.cpp
 * @author  Xiao Pan (pan@cs.uni-kl.de)
 * @date    10:46:05 Apr 16 2018
 * @section LICENSE License (ADD YOUR LICENSE HERE)
 *  
 * @section DESCRIPTION Description (ADD YOUR DESCRIPTION HERE)
 *          Example project of [XML2AMS]
 * 
 */


#include "sca_tdf_gnd.h"

//  
//! Custom Constructor 
//  
sca_tdf_gnd::sca_tdf_gnd(sc_core::sc_module_name nm )
{
	 // Local variables store module parameters

}

//
// set_attributes()
//
void  sca_tdf_gnd::set_attributes(){ /* Insert your  code here */    }

//
// initialize()
//
void  sca_tdf_gnd::initialize(){ /* Insert your  code here */    }

//
// processing()
//
void sca_tdf_gnd::processing(){
    //<<< START OF USER-ADDED-CODE >>>>
    pout_gnd.write(0);
    //<<< END OF USER-ADDED-CODE >>>
}

//
// change_attributes()
//
// void  sca_tdf_gnd::change_attributes(){ /* Insert your  code here */    }

//
// ac_processing()
//
// void  sca_tdf_gnd::ac_processing(){  /* Insert your  code here */    }

//
// end_of_simulation()
//
// void sca_tdf_gnd::end_of_simulation(){ /* Insert your  code here */    }

