/**
 * @file    insert_file_header_info.cpp
 * @author  Xiao Pan 
 * @date    06-04-2018
 *
 * Copyright (c) 2012-2018 Design of Cyber-Physical Systems TU Kaiserslautern
 * Contact: Xiao Pan <pan@cs.uni-kl.de | xml2sca@panxiao.tech>
 *
 * @section LICENSE License
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @section DESCRIPTION
 * XML2SCA : Auto-generate SystemC/SystemC-AMS projects (incl. codes,
 * testbenches, cmakes) from XML file. <https://github.com/panxiao-tech/XML2SCA>
 *
 */

#include "insert_file_header_info.h"

namespace xml2sca
{
    // -------------------------------------------------------------------------
    //! insert_file_header_info
    // -------------------------------------------------------------------------
    void insert_file_header_info(std::unique_ptr<std::ostream> &_pstrFile,
                                 string _filename,
                                 ams_project_data::proj_info _proj_info)
    {
        // file header information
        *_pstrFile<<"/**"  <<endl;
        *_pstrFile<<" * This file is automatically generated from [XML2SCA] "<<endl;
        *_pstrFile<<" * https://github.com/panxiao-tech/XML2SCA" <<endl;
        *_pstrFile<<" * Contact: Xiao Pan <pan@cs.uni-kl.de | xml2sca@panxiao.tech>" <<endl;
        *_pstrFile<<" * " <<endl;
        *_pstrFile<<" * @file    "<<  _filename <<endl;
        *_pstrFile<<" * @author  "<<  _proj_info.author <<endl;
        *_pstrFile<<" * @date    "<<  __TIME__ <<" "<< __DATE__ <<endl;
        *_pstrFile<<" * @section "<< "LICENSE License (ADD YOUR LICENSE HERE)" <<endl;
        *_pstrFile<<" *  "     <<endl;
        *_pstrFile<<" * @section "<< "DESCRIPTION Description (ADD YOUR DESCRIPTION HERE)" <<endl;
        *_pstrFile<<" *          "<<  _proj_info.description            <<endl;
        *_pstrFile<<" * "    <<endl;
        *_pstrFile<<" */"    <<endl <<endl <<endl ;
    }
    
}

